### ISSUE TITLE
Mixxx - EOS.

### ISSUE THREAD

**Issue by dfsdiogo** [flathub/org.mixxx.Mixxx#1]
The program doesn't run after installation on Endless OS.
[eos-diagnostic-190629_212711_UTC-0300.txt](https://github.com/flathub/org.mixxx.Mixxx/files/3342405/eos-diagnostic-190629_212711_UTC-0300.txt)

EOS Diagnostics attached.

**Comment by FakeShemp** [comment]
It might be solved with https://github.com/flathub/org.mixxx.Mixxx/pull/3. Please try it out :)

**Comment by LeandroStanger** [comment]
The Mixxx does not open in Endless OS

**Comment by FakeShemp** [comment]
I need more to go on. Is there any error messages?

**Comment by LeandroStanger** [comment]
No
![Captura de tela de 2019-08-12 09-56-00](https://user-images.githubusercontent.com/26097419/62866563-6e916380-bce7-11e9-9b2a-142a1de138ce.png)

**Comment by FakeShemp** [comment]
Does it work without Wayland?

**Comment by LeandroStanger** [comment]
```
Does it work without Wayland?
```
X11

**Comment by FakeShemp** [comment]
What does that mean?

**Comment by ramcq** [comment]
Endless uses X11 by default at the moment, never Wayland. It works OK for me here on Endless OS 3.6.2.

**Comment by LeandroStanger** [comment]
This has been fixed with the last update

**Comment by Erick555** [comment]
@FakeShemp considering above comment you may close this one.
