### ISSUE TITLE
Not listed at flathub.org

### ISSUE THREAD

**Issue by jgarciao** [flathub/org.mixxx.Mixxx#10]
This app is not listed in Flathub, https://flathub.org/apps/details/org.mixxx.Mixxx shows an empty page

The reason is because this application appears with `component type="generic"` in flatpak appstream.xml  file. It should be `component type="desktop"` or `component type="desktop-application"`

It's a little strange because the apps appdata file seems [fine in the app repo](https://github.com/mixxxdj/mixxx/blob/master/res/linux/mixxx.appdata.xml). 

Maybe this was merged for version 2.2.2?

**Comment by jgarciao** [comment]
It seems to be still wrong after the new build

```
$ flatpak update --appstream
Updating appstream data for remote flathub


$ flatpak info org.mixxx.Mixxx

Mixxx DJ Software - Everything you need to perform live DJ mixes

          ID: org.mixxx.Mixxx
         Ref: app/org.mixxx.Mixxx/x86_64/stable
        Arch: x86_64
      Branch: stable
     License: GPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 63,0 MB
     Runtime: org.kde.Platform/x86_64/5.12
         Sdk: org.kde.Sdk/x86_64/5.12

      Commit: 5a5dfdef378d0d30ccc7c1dcddc06a71e4b891eee9f0e986572830097f236870
      Parent: b6fd7c5e4f6e9b4bd5776677337f92ce9514ebcf3ccf2a3fa6bc69b65035a4d8
     Subject: Update to 2.2.2 (0b2e80bc)
        Date: 2019-09-17 12:28:54 +0000


$ grep  -a1 "<id>org.mixxx.Mixxx" /var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml 
  </component><component type="generic">
    <id>org.mixxx.Mixxx</id>
    <name>Mixxx DJ Software</name>

```

**Comment by FakeShemp** [comment]
As far as I can tell its correct when built. Is this a flathub issue?

**Comment by jgarciao** [comment]
Is only happening with this app. Maybe @barthalion can help us find the problem

**Comment by LeandroStanger** [comment]
This has been fixed with the last update
![Captura de tela de 2019-10-27 10-05-59](https://user-images.githubusercontent.com/26097419/67635072-689c2f00-f8a1-11e9-869d-76be9221b02e.png)

**Comment by Erick555** [comment]
@FakeShemp you can close this one but please patch [appdata further](https://github.com/flathub/org.mixxx.Mixxx/pull/14#issuecomment-546619814) (ideally send patches upstream as you did before) and remove [workaround](https://github.com/flathub/org.mixxx.Mixxx/commit/2d05c14fcbfcf99ed89fba1565f29be3305450c2).

**Comment by jgarciao** [comment]
Thank you!
