### ISSUE TITLE
Icecast support broken due to libshout bug

### ISSUE THREAD

**Issue by rowbawts** [flathub/org.mixxx.Mixxx#17]
So icecast won't connect due to a bug in the libshout version used in this Flatpak as documented [here](https://gitlab.xiph.org/xiph/icecast-libshout/issues/2308) not sure if this can be fixed by you guys but this issue has been fixed in newer releases

Edit: More information [here](https://www.mixxx.org/forums/viewtopic.php?f=3&t=12781)

**Comment by hfiguiere** [comment]
If there are patches to apply to the current release, it is possible.

**Comment by davy39** [comment]
Hi, 
Waiting for 2.4.4 release, would it be possible to use the master git version of icecast-libshout and submodules, it seems to correct this bug since [this commit](https://gitlab.xiph.org/xiph/icecast-libshout/commit/0ac7ed9e84c3871d4427acc1ce59dca5e4af21ef).
Thank you !

**Comment by Be-ing** [comment]
We are ditching libshout for a fork of libshout 2.4.1 from IDJC that supports using fdk-aac for AAC encoding which upstream refuses to support and they are awful about fixing critical bugs.
