### ISSUE TITLE
JACK support

### ISSUE THREAD

**Issue by SolarLiner** [flathub/org.mixxx.Mixxx#19]
Access to `/dev/shm` is explicitely blacklisted for sandboxed apps, which means using `--filesystem=/dev/shm` does not expose JACK sockets to the sandbox; and neither does `--device=all`.

A special `--device=shm` permission will land in Flatpak 1.6.1 to support the workaround, but the longer term solution is to use PipeWire through its JACK extension.

This issue is blocked by https://github.com/flatpak/flatpak/issues/1509.

**Comment by hfiguiere** [comment]
The only way to support jack is to use the pw-jack. This can be done with the 5.15 runtime (Freedesktop 20.08)

**Comment by hfiguiere** [comment]
Since #26 it should be doable.
