### ISSUE TITLE
access to HID devices

### ISSUE THREAD

**Issue by Be-ing** [flathub/org.mixxx.Mixxx#32]
Mixxx ships with a [udev rule file](https://github.com/mixxxdj/mixxx/blob/43d83fb5ce37646dcd05fb11e47e5a99cbe8160b/res/linux/mixxx-usb-uaccess.rules) to give unprivileged users permission to access HID DJ controllers... how can that be done with Flatpak?

**Comment by hfiguiere** [comment]
I don't think it can be done, because Sandboxing.

**Comment by Be-ing** [comment]
That's unfortunate. I was hoping we could use Flatpak for official builds upstream, but I guess we won't be able to do that as long as this remains unresolved.

**Comment by hfiguiere** [comment]
sandboxing breaks a lot of assumption made in the last decades on how OS work.

**Comment by Be-ing** [comment]
https://github.com/flatpak/flatpak/issues/3291

**Comment by Be-ing** [comment]
https://github.com/systemd/systemd/pull/20561

**Comment by Be-ing** [comment]
This was fixed upstream in systemd https://github.com/systemd/systemd/pull/22730

**Comment by Be-ing** [comment]
https://github.com/systemd/systemd/pull/22730 was not sufficient to get this to work. https://github.com/systemd/systemd/pull/30611 is also required, though this fix hasn't been included in a systemd release yet. Reopening this until the next systemd release.

**Comment by Be-ing** [comment]
The fix has been backported to systemd stable releases back to 252.
