### ISSUE TITLE
mixxx mutes all other apps

### ISSUE THREAD

**Issue by ghost** [flathub/org.mixxx.Mixxx#9]
thanks for fixing the previous issue (opus support, so cool how you fixed that)

if I install mixxx through a traditional package manager it mutes all other audio from other apps

But i just edit mixxx.desktop and this is addressed in the mixxx troubleshooting

the same thing happens with the flathub Mixxx but I'm not aware if it's possible to fix

**Comment by eszlari** [comment]
In what way do you modify mixxx.desktop?

**Comment by ronso0** [comment]
[mixxx.desktop](https://github.com/mixxxdj/mixxx/blob/master/build/debian/mixxx.desktop) runs `pasuspender` before starting Mixxx so it gains access to all sound devices previously managed by pulse (and maybe occupied).
wiki: [Other programs do not make sound while Mixxx is running](https://www.mixxx.org/wiki/doku.php/troubleshooting#other_programs_do_not_make_sound_while_mixxx_is_running)

**Comment by Be-ing** [comment]
Suspending PulseAudio is intended. If you don't want that, switch to PipeWire and use PipeWire via Mixxx's JACK backend.
